#!/bin/bash
# install-hook.sh — Install the security pre-commit hook in the current git repo.
#
# Run from anywhere within the target repo. Generates `.git/hooks/pre-commit`
# pointing to scan.sh in this skill's scripts/ directory (via absolute path).
#
# Idempotent: re-running just overwrites the hook.
#
# Usage:
#   /path/to/skills/tools/security-precommit-check/scripts/install-hook.sh

set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SCAN_SH="$SCRIPT_DIR/scan.sh"

if [ ! -f "$SCAN_SH" ]; then
  echo "install-hook.sh: scan.sh not found at $SCAN_SH" >&2
  exit 1
fi

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" || {
  echo "install-hook.sh: not inside a git repository" >&2
  exit 1
}

HOOK_PATH="$REPO_ROOT/.git/hooks/pre-commit"

cat > "$HOOK_PATH" << EOF
#!/bin/bash
# Auto-generated by tools/security-precommit-check/scripts/install-hook.sh
# Calls the central scanner against staged files.
exec "$SCAN_SH" --staged
EOF

chmod +x "$HOOK_PATH"

# Per-repo rules — create empty file with template if missing
PROJECT_RULES="$REPO_ROOT/.security-precommit-rules.txt"
if [ ! -f "$PROJECT_RULES" ]; then
  TEMPLATE="$SCRIPT_DIR/../templates/security-precommit-rules.txt.example"
  if [ -f "$TEMPLATE" ]; then
    cp "$TEMPLATE" "$PROJECT_RULES"
    echo "Created template: $PROJECT_RULES (edit to add per-repo rules)"
  fi
fi

echo "Installed pre-commit hook → $HOOK_PATH"
echo "  → calls: $SCAN_SH --staged"
echo "  → reads default rules from $SCRIPT_DIR/../rules/default.txt"
echo "  → reads per-repo rules from $PROJECT_RULES (if exists)"
echo
echo "Test it:"
echo "  $SCAN_SH --all"
